apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kks-provider-plugin.fullname" . }}-driver
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kks-provider-plugin.labels" . | nindent 4 }}
data:
  driver.hcl: |
    driver {}
    client {}
