{{- if .Values.lb.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kks-provider-plugin.lbServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kks-provider-plugin.labels" . | nindent 4 }}
{{- end }}
