{{- include "kks-provider-plugin.validateRequired" . }}
{{- if not .Values.lb.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kks-provider-plugin.lbSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kks-provider-plugin.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.lb.existingSecretAccessTokenKey }}: {{ required "lb.accessToken is required when lb.existingSecret is not set" .Values.lb.accessToken | quote }}
{{- end }}
{{- if and (not .Values.lb.existingSecret) (not .Values.csi.existingSecret) }}
---
{{- end }}
{{- if not .Values.csi.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kks-provider-plugin.csiSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kks-provider-plugin.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.csi.existingSecretAccessTokenKey }}: {{ required "csi.accessToken is required when csi.existingSecret is not set" .Values.csi.accessToken | quote }}
{{- end }}
