apiVersion: v2
name: kloud-csi
description: Kloud CSI driver for kks persistent volumes
type: application
version: 0.1.0
appVersion: "0.1.0"
kubeVersion: ">=1.28.0-0"
home: https://github.com/KubelanCloud/kks-csi-plugin
keywords:
  - csi
  - storage
  - kloud
maintainers:
  - name: Kloud Team
